name: Login
version: '1.0'
main: org.trixder.login.Login
api-version: '1.21'
commands:
  loginreload:
    description: Reloads the plugin
    usage: /loginreload
    permission: login.admin
    permission-message: You do not have permission to use this command.
  logout:
    description: Log out
    usage: /logout
permissions:
  login.normal:
    description: Allows the player to use the some /login commands
    default: true
  login.use:
    description: Allows the player to use the /login commands
    default: true
  login.admin:
    description: Allows the player to use /login admin commands
    default: op